CREATE DATABASE Timedb;

CREATE USER 'admin'@'%' IDENTIFIED BY '1234';

CREATE TABLE Timedb.TimeData (
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
Date DATETIME NOT NULL,
Number INT  NOT NULL);

GRANT ALL PRIVILEGES ON * . * TO 'admin'@'%';