apiVersion: v1
kind: PersistentVolume
metadata:
  name: base-volume
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: base-volume-claim
spec:
  storageClassName: hostpath
  volumeName: base-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi