---
apiVersion: v1
kind: Service
metadata:
  name: base-service
  labels:
    app: ms-base
spec:
  type: NodePort
  selector:
    app: ms-base
  ports:
    - protocol: TCP
      name: http
      port: 5000
      targetPort: 5000
      nodePort: 30004 # Parametro opcional
