---
# Deploy de ms-base
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-base-deploy
  labels:
    app: ms-base
spec:
  selector:
    matchLabels:
      app: ms-base
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: ms-base
    spec:
      containers:
        - name: ms-base
          image: acjimeneza/ms-base:2
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          volumeMounts:
            - name: configuration-from-cm
              mountPath: app/Configuration/appsettings.Development.json
              subPath: appsettings.Development.json
      volumes:
        - name: configuration-from-cm
          configMap:
            name: base-configmap
            items:
              - key: "appsettings.Development.json"
                path: "appsettings.Development.json"

---
# Servicio para el deploy de ms-base
apiVersion: v1
kind: Service
metadata:
  name: base-service
  labels:
    app: ms-base
spec:
  type: LoadBalancer
  selector:
    app: ms-base
  ports:
    - protocol: TCP
      name: http
      port: 8000
      targetPort: 5000

---
# Deploy de MYSql
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: acjimeneza/mysql:1
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "1234"
            - name: MYSQL_USER
              value: admin
            - name: MYSQL_PASSWORD
              value: "1234"
            - name: MYSQL_DATABASE
              value: Timedb
          imagePullPolicy: Always
          ports:
            - containerPort: 3306
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "400m"

---
# Servicio para el deploy de MYSql
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: mysql
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
    - protocol: TCP
      name: http
      port: 3306
      targetPort: 3306